### ISSUE TITLE
java.io.FileNotFoundException: src\main\resources\slackemojis.config

### ISSUE THREAD

**Issue by RoboMWM** [wollekuel/slack2irc-bridge#11]
```
2017-07-14 21:23:47,169 main ERROR Unable to locate appender "SESSIONOptimizer"
for logger config "root"
java.io.FileNotFoundException: src\main\resources\slackemojis.config (The system cannot find the path specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileInputStream.<init>(Unknown Source)
        at java.io.FileReader.<init>(Unknown Source)
        at de.justeazy.slack2irc.irc.IrcBot.<init>(IrcBot.java:76)
        at de.justeazy.slack2irc.Slack2IrcBridge.<init>(Slack2IrcBridge.java:73)

        at de.justeazy.slack2irc.Slack2IrcBridge.main(Slack2IrcBridge.java:227)
Error starting the bridge.
```

O well.

**Comment by wollekuel** [comment]
Thanks for the input. I'm trying to figure that one out soon...

**Comment by wollekuel** [comment]
Should be fixed.
